#! /bin/sh

DRYRUN=true

parse() {
	while [ "$1" ]
	do
		ARGS=(`echo $1 | tr '=' ' '`) 
		shift
		case ${ARGS[0]:2} in
			"tag")
				BRANCH=${ARGS[1]}
				;;
			"release_ver")
				RELEASE=${ARGS[1]}
				;;
			"dev_ver")
				DEV=${ARGS[1]}
				;;
			"user")
				SVN_USER=${ARGS[1]}
				;;
			"password")
				SVN_PWD=${ARGS[1]}
				;;
		esac
	done
}

verify() {
	VAR=$(eval echo \$$1)
	if [ -z "${VAR}" ]
	then
		echo $2
		MISSING=true
	fi
}

parse $*
verify BRANCH "Missing --tag option (e.g., 1_2_3)"
verify RELEASE "Missing --release_ver option (e.g., 1.2.3)"
verify DEV "Missing --dev_ver option (e.g., 1.2.4-SNAPSHOT)"
verify SVN_USER "Missing --user option for your svn user name"
verify SVN_PWD "Missing --password option for your svn password"
[ "${MISSING}" ] && exit

cat > settings.xml << EOF
<settings>
	<servers>
		<server>
			<id>rator.sfbay</id>
			<username>${SVN_USER}</username>
			<password>${SVN_PWD}</password>
		</server>
	</servers>
</settings>
EOF

mvn -e -P release-profile -DdryRun=$DRYRUN -DautoVersionSubmodules=true -DdevelopmentVersion=${DEV} -DreleaseVersion=${RELEASE} -Dtag=${BRANCH} -Dpassword=${SVN_PWD} -Dusername=${SVN_USER} release:clean release:prepare release:perform

