
package org.glassfish.grizzly.jaxws.addclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddServiceService", targetNamespace = "http://jaxws.grizzly.glassfish.org/", wsdlLocation = "http://localhost:19881/add?wsdl")
public class AddServiceService
    extends Service
{

    private final static URL ADDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDSERVICESERVICE_EXCEPTION;
    private final static QName ADDSERVICESERVICE_QNAME = new QName("http://jaxws.grizzly.glassfish.org/", "AddServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:19881/add?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDSERVICESERVICE_WSDL_LOCATION = url;
        ADDSERVICESERVICE_EXCEPTION = e;
    }

    public AddServiceService() {
        super(__getWsdlLocation(), ADDSERVICESERVICE_QNAME);
    }

    public AddServiceService(URL wsdlLocation) {
        super(wsdlLocation, ADDSERVICESERVICE_QNAME);
    }

    public AddServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AddService
     */
    @WebEndpoint(name = "AddServicePort")
    public AddService getAddServicePort() {
        return super.getPort(new QName("http://jaxws.grizzly.glassfish.org/", "AddServicePort"), AddService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddService
     */
    @WebEndpoint(name = "AddServicePort")
    public AddService getAddServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.grizzly.glassfish.org/", "AddServicePort"), AddService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDSERVICESERVICE_EXCEPTION!= null) {
            throw ADDSERVICESERVICE_EXCEPTION;
        }
        return ADDSERVICESERVICE_WSDL_LOCATION;
    }

}
