
package org.glassfish.grizzly.jaxws.addclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddService", targetNamespace = "http://jaxws.grizzly.glassfish.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddService {


    /**
     * 
     * @param value1
     * @param value2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://jaxws.grizzly.glassfish.org/", className = "org.glassfish.grizzly.jaxws.addclient.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://jaxws.grizzly.glassfish.org/", className = "org.glassfish.grizzly.jaxws.addclient.AddResponse")
    public int add(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

}
